name: Terraform Deploy - Staging

on:
  push:
    paths:
      - 'envs/staging/**'
    branches:
      - master  # Adjust if you use a different branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -var="git_sha=${{ github.sha }}" -var-file="terraform.tfvars"
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var="git_sha=${{ github.sha }}" -var-file="terraform.tfvars"
